export const stages = ["new", "qualified", "contacted", "converted"];

export const demoStepTemplate = [
  "Lead recibido...",
  "Analizando intención...",
  "Lead calificado: CALIENTE / TIBIO / FRÍO",
  "Enviado al CRM",
  "Automatización activada",
];

export const demoLeads = [
  {
    name: "Camila Torres",
    business: "Nova Studio",
    phone: "+57 300 421 9090",
    service: "Automatización de WhatsApp",
    message: "Quiero responder clientes y agendar más rápido esta semana.",
    source: "live_demo",
    score: 92,
    classification: "hot",
    scoreReasons: ["alta urgencia", "intención de compra", "automatización de whatsapp"],
    workflow: "whatsapp_qualification",
  },
  {
    name: "Andrés Molina",
    business: "LegalHub",
    phone: "+57 310 884 1200",
    service: "CRM automatizado",
    message: "Necesitamos ordenar prospectos y seguimiento comercial.",
    source: "live_demo",
    score: 74,
    classification: "warm",
    scoreReasons: ["necesidad de crm", "intención operativa", "falta de seguimiento"],
    workflow: "crm_sync",
  },
  {
    name: "Sofía Rivas",
    business: "EducaPro",
    phone: "+57 315 330 7711",
    service: "Chatbot IA para ventas",
    message: "Estoy revisando opciones para automatizar información de cursos.",
    source: "live_demo",
    score: 48,
    classification: "cold",
    scoreReasons: ["etapa de investigación", "baja urgencia", "caso de uso educativo"],
    workflow: "nurture_sequence",
  },
];

export const state = {
  leads: [],
  demoLeads: [],
  actions: [],
  demoActions: [],
  notifications: [],
  events: [],
  demoEvents: [],
  storage: "checking",
  health: null,
  user: null,
  billing: null,
  settings: null,
  invitations: [],
  selectedLeadId: null,
  selectedIds: new Set(),
  members: [],
  filter: "all",
  statusFilter: "all",
  searchQuery: "",
  smartFilter: "all",
  reportDays: 30,
  hydrated: false,
  loadedOnce: false,
  refreshing: false,
  newEventIds: new Set(),
  newLeadIds: new Set(),
  updatedStages: new Set(),
  demo: {
    active: false,
    running: false,
    currentLeadId: null,
    currentStep: -1,
    selectedIndex: 0,
    timers: [],
  },
};
